server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 👇 핵심! 파일이 없으면 index.html로 연결 (React가 처리하도록)
        try_files $uri $uri/ /index.html;
    }
}
