scan_filter_chain:
  - name: body_box_filter
    type: laser_filters/LaserScanBoxFilter
    params:
      box_frame: laser_frame # 라이다 기준 좌표계
      # 라이다 위치를 기준으로 본체가 차지하는 영역(미터 단위)
      min_x: -0.30 # 라이다 뒤쪽으로 25cm까지 본체라면
      max_x: 0.20  # 라이다 앞쪽으로 5cm까지 본체라면
      min_y: -0.20 # 좌측 15cm
      max_y: 0.20  # 우측 15cm
      min_z: -0.10
      max_z: 0.10
