services:
  # 1. Database: PostgreSQL
  postgres:
    image: postgres:15
    container_name: robot_db
    restart: always
    environment:
      POSTGRES_DB: robot_db
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - robot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d robot_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. MQTT Broker: Mosquitto
  robot_mqtt:
    image: eclipse-mosquitto:2.0
    container_name: robot_mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - robot_network

  # 3. Backend: Spring Boot
  robot_server:
    build: ./server
    container_name: robot_server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      robot_mqtt:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/robot_db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

      MQTT_BROKER_URL: tcp://robot_mqtt:1883
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    networks:
      - robot_network
  
  # 4. Frontend: React Client
  robot_client:
    build: ./client
    container_name: robot_client
    restart: always
    stdin_open: true
    tty: true
    networks:
      - robot_network
  
  # 5. Gateway: Nginx
  robot_nginx:
    build: ./nginx
    container_name: robot_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./uploads:/var/www/uploads
    depends_on:
      - robot_client
      - robot_server
      - robot_mqtt
    networks:
      - robot_network
  
  robot_media:
    image: bluenviron/mediamtx:latest
    container_name: robot_media
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "8889:8889"
      - "8888:8888"
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=i14c203.p.ssafy.io
    networks:
      - robot_network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait &&{!}; done;'"
    networks:
      - robot_network

networks:
  robot_network:
    driver: bridge
