upstream client {
    server robot_client:80;
}

upstream backend {
    server robot_server:8080;
}

server {
    listen 80;
    server_name i14c203.p.ssafy.io;

    location / {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name i14c203.p.ssafy.io;

    ssl_certificate /etc/letsencrypt/live/i14c203.p.ssafy.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/i14c203.p.ssafy.io/privkey.pem;

    # 1. 프론트엔드 (React)
    location / {
        proxy_pass http://client;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. 백엔드 API (Spring Boot)
    location /api {
        rewrite ^/api/(.*)$ /$1 break;

        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. 웹소켓 (STOMP - 로봇 데이터)
    location /ws {
        proxy_pass http://backend/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # 4. 웹소켓 (WebRTC - 영상 통화)
    location /signal {
        proxy_pass http://backend/signal;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # [5] 웹소켓 (자율주행차 통신 - ROS2)
    location /ros2 {
        proxy_pass http://backend/ros2;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # [6] 이미지/동영상 갤러리 (저장소)
    location /uploads {
        alias /var/www/uploads;
        autoindex off;
        access_log off;
    }
}
